spring.application.name=finance-data-processing

# Active Profile
spring.profiles.active=dev

# Common JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect